### ISSUE TITLE
cffi 2.0b1 not running on Linux with Tcl9

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-cffi#205]
On Linux cffi compiles using Tcl 8.6.15 and Tcl 9.

Test suite runs fine with 8.6.15.

Using Tcl 9 the following errors occur:
Test file error: couldn't load file "/home/obermeier/poSoft/BawtBuild-9.0.0-9.0.0-Release/Linux/x64/Release/Build/cffi/libtcl9cffi2.0b1.so": /home/obermeier/poSoft/BawtBuild-9.0.0-9.0.0-Release/Linux/x64/Release/Build/cffi/libtcl9cffi2.0b1.so: undefined symbol: mp_clear
    while executing
"load /home/obermeier/poSoft/BawtBuild-9.0.0-9.0.0-Release/Linux/x64/Release/Build/cffi/libtcl9cffi2.0b1.so Cffi"

**Comment by apnadkarni** [comment]
This again sounds like a tommath configuration error as the Github [CI](https://github.com/apnadkarni/tcl-cffi/actions/runs/11138817195) runs without failures. That is Ubuntu 20.04 but I've also tested against Ubuntu 22.

I need to get clarity on how extensions need to link against tommath given that Tcl may be built either way (--with-system-tommath) option.

**Comment by apnadkarni** [comment]
Fixed by removing depending on libtommath. Please verify and if getting failures, what version of Linux.

**Comment by PaulObermeier** [comment]
Now builds fine and all tests succeed on various Linux systems.

A build error using gcc 14 came up with your changes in tclhUuidImpl.c when replacing ckalloc/ckfree with Tcl_Alloc/Tcl_Free.
Example:
./tclh/include/tclhUuidImpl.c: In function ‘SetUuidObjFromAny’:
./tclh/include/tclhUuidImpl.c:133:11: error: assignment to ‘Tclh_UUID *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
  133 |     uuidP = Tcl_Alloc(sizeof(*uuidP));

If adding appropriate casts, cffi compiles and runs fine with gcc 14 (ex. Fedora 40).
