### ISSUE TITLE
Build errors using cffi 2.0b1 and Tcl 8.7

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/tcl-cffi#212]
As discussed in the last VideoCon, I tried the combination Tcl 8.7 and Tk 9.
cffi fails with the following errors - using MinGW gcc 7.2.0 and core-8-branch as of yesterday:

./tclh/include/tclhObjImpl.c: In function 'Tclh_ObjToULongLong':
./tclh/include/tclhObjImpl.c:326:9: error: unknown type name 'mp_int'; did you mean 'u_int'?
         mp_int temp;
         ^~~~~~
         u_int
./tclh/include/tclhObjImpl.c:329:28: error: request for member 'sign' in something not a structure or union
             int sign = temp.sign;
                            ^
./tclh/include/tclhObjImpl.c:331:25: error: 'MP_NEG' undeclared (first use in this function); did you mean 'MP_8mm'?
             if (sign == MP_NEG)

You have macros to detect Tcl 8.7, but these do not seem to be used consequently.
Paul

**Comment by apnadkarni** [comment]
Paul, to help track down the source of this, have you compiled cffi with the *same* gcc version against 8.6 and 9.0? Did you see the same failure?

The linking against tommath has been a continuing source of mystery for me. It has been changed between 8.6 (where Tcl used its own internal mechanism) and 9.0 (where it could use either). Cffi of course builds against either currently but I don't how 8.7 is configured with respect to tommath.

/Ashok

**Comment by PaulObermeier** [comment]
Using the same compiler it works with 8.6 and 9.0.

The problem seems to be the masking of mp_int.
In function Tclh_ObjLibInit you are using the following macro:
#ifdef TCLH_TCL87API
#else
    mp_int temp;
#endif

But you are using mp_int in Tclh_ObjToWideInt, which is masked with:
#if TCL_MAJOR_VERSION < 9

**Comment by apnadkarni** [comment]
The non-use of `TCLH_TCL87API` in this instance was intentional due to my *mistaken* assumption that `Tcl_GetWideIntFromObj` in 8.7 followed 8.6 binary compatibility semantics, not the 8.7/9.0 *source* API which is what `TCLH_TCL87API` refers to.

Fixed now (in the tclh submodule). Thanks for the pointer to fix.

**Comment by apnadkarni** [comment]
tclh updated to fix the missing casts.

I changed from ckalloc to Tcl_Alloc as I was told the former was deprecated (it's no longer documented either). I think that was a mistake because now casts are needed all over the place. In any case, I've added the casts now.

How do you test with multiple gcc versions? Do you have multiple VM's or systems or is it possible to have multiple gcc versions on a single box? If I try to update gcc on my Ubuntu, it says you already have the latest version (11).

**Comment by PaulObermeier** [comment]
Hi Ashok,

For Windows I have different gcc versions on a Win11 laptop.
For Linux I have a laptop with 3 different distributions as well as lots of virtual machines.
I also have two MacBooks, a Raspi and a RiscV system.

Here is the complete list of systems I have available for testing:
```
                   gcc --version  uname -r        XDG_CURRENT_DESKTOP  XDG_SESSION_TYPE
Windows MinGW       7.2.0         3.0.7-338
Windows MinGW       8.1.0         3.0.7-338
Windows MinGW      11.2.0         3.3.4-341
Windows MinGW      12.2.0         3.4.6.x86_64
Windows MinGW      13.2.0         3.4.10.x86_64
Windows MinGW      14.2.0         3.5.3.x86_64 

SUSE 42.3 (VM)      4.8.5         4.4.179         KDE                  x11
SUSE 15.5           7.5.0         5.14.21         KDE                  x11
SUSE 15.6 (VM)      7.5.0         6.4.0           KDE                  x11
SUSE Tumble (VM)   14.2.0         6.10.11         XFCE                 x11

Debian  8.6  (VM)   4.9.2         3.16.0-5        KDE                  x11
Debian 11.6  (VM)  10.2.1         5.10.0-20       GNOME                wayland
Debian 12.0  (VM)  12.2.0         6.1.0-9         GNOME                wayland
Debian 12.4        12.2.0         6.1.0-16        GNOME                x11
Debian 12.6  (VM)  12.2.0         6.1.0-25        GNOME                wayland

Ubuntu 20.04 (VM)   9.4.0         5.15.0-73       GNOME                x11
Ubuntu 23.04 (VM)  12.2.0         6.2.0-20        GNOME                wayland
Ubuntu 23.10       13.2.0         6.5.0-44        GNOME                x11
Ubuntu 24.04 (VM)  13.2.0         6.8.0-31        GNOME                wayland

Fedora 38.1 (VM)   13.1.1         6.3.7-200       GNOME                wayland
Fedora 39.1 (VM)   13.2.1         6.6.8-200       GNOME                wayland
Fedora 40.1 (VM)   14.0.1         6.8.5-301       GNOME                wayland

Big Sur 11.7.10    13.0.0         20.6.0 
Sonoma 14.7        15.0.0         23.6.0

Raspberry Pi OS    12.2.0         6.1.0-rpi8      NotSet               wayland
Risc-V             12.2.0         5.15.0-starfive GNOME                wayland
```
